apiVersion: v1
kind: ConfigMap
metadata:
  name: coredns
  namespace: kube-system
data:
  Corefile: |-
    .:53 {
        cache 30
        etcd a4r.site. {
          path /skydns
          endpoint http://etcd-client-service-lb.core:2379
        }
        health
        loadbalance round_robin
        proxy . /etc/resolv.conf
    }