apiVersion: v1
kind: Service
metadata:
  name: coredns
  namespace: default
  labels:
    app: coredns
spec:
  selector:
    app: coredns
  ports:
  - name: dns
    nodePort: 30053
    port: 53
    protocol: UDP
    targetPort: 53
  - name: dns-tcp
    nodePort: 30053
    port: 53
    protocol: TCP
    targetPort: 53
  type: NodePort
